# Generated by Django 4.2.24 on 2025-09-06 18:32

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                default=accounts.models.User.get_default_role,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.role",
            ),
        ),
    ]
