# Generated by Django 4.2.24 on 2025-09-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="name",
            field=models.CharField(
                blank=True, default="Guest", max_length=30, null=True
            ),
        ),
    ]
