# Generated by Django 4.2.24 on 2025-09-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0003_alter_projectimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectimage",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="project_images/"),
        ),
    ]
